"use server";

import fs from "node:fs/promises";
import path from "node:path";
import { getFileContent, exportFileAsPdf, getFileBinary } from "../lib/google-drive";

const INDEX_FILE = path.join(process.cwd(), "output", "patient-index.json");
const LETTERS_INDEX_FILE = path.join(process.cwd(), "output", "letters-index.json");

export type PatientIndexEntry = {
  name: string;
  surname: string;
  firstname: string;
  dob: string;
  sex: string;
  urn: string;
  phone: string;
  suburb: string;
  file: string;
  filePath: string; // Google Drive File ID
};

export async function getPatientIndex(): Promise<PatientIndexEntry[]> {
  try {
    // Index is stored locally (generated by sync-google-drive.mjs and committed to Git)
    const raw = await fs.readFile(INDEX_FILE, "utf8");
    return JSON.parse(raw) as PatientIndexEntry[];
  } catch (error) {
    console.error("Patient index not found. Run: node scripts/sync-google-drive.mjs", error);
    return [];
  }
}

export type LetterIndexEntry = {
  fileId: string;
  fileName: string;
  mimeType: string;
};

export async function getLettersIndex(): Promise<Record<string, LetterIndexEntry>> {
  try {
    const raw = await fs.readFile(LETTERS_INDEX_FILE, "utf8");
    return JSON.parse(raw) as Record<string, LetterIndexEntry>;
  } catch (error) {
    console.error("Letters index not found. Run: node scripts/build-letters-index.mjs", error);
    return {};
  }
}

export async function readBackupFile(fileId: string) {
  try {
    if (!fileId) {
      throw new Error("No File ID provided.");
    }
    // Individual XML files are fetched from Google Drive on demand
    const content = await getFileContent(fileId);
    return {
      name: "Patient Record",
      content,
    };
  } catch (error) {
    console.error("Error reading file from Drive:", error);
    throw error;
  }
}

export async function getLetterPdf(fileId: string) {
  try {
    const pdfBuffer = await exportFileAsPdf(fileId);
    return pdfBuffer.toString("base64");
  } catch (error) {
    console.error("Error exporting letter as PDF:", error);
    throw error;
  }
}

export async function getLetterDownload(fileId: string) {
  try {
    const buffer = await getFileBinary(fileId);
    return buffer.toString("base64");
  } catch (error) {
    console.error("Error downloading letter:", error);
    throw error;
  }
}

export async function login(password: string) {
  const correctPassword = process.env.APP_PASSWORD;
  if (!correctPassword) return true;

  if (password === correctPassword) {
    const { cookies } = await import("next/headers");
    (await cookies()).set("session", password, {
      httpOnly: true,
      secure: process.env.NODE_ENV === "production",
      maxAge: 60 * 60 * 24 * 7, // 1 week
      path: "/",
    });
    return true;
  }
  return false;
}
